// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAR3B23ioi0PCCVe2m_RULwogjWqe4we8',
    appId: '1:537962552829:web:558d812f0b5e1876ed8d94',
    messagingSenderId: '537962552829',
    projectId: 'fashion-store-bbdda',
    authDomain: 'fashion-store-bbdda.firebaseapp.com',
    storageBucket: 'fashion-store-bbdda.firebasestorage.app',
    measurementId: 'G-KVLVJFL5GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW-gyd1GUyHYIiF98TNSdM-gggAsEXFN4',
    appId: '1:537962552829:android:791c588d023bca15ed8d94',
    messagingSenderId: '537962552829',
    projectId: 'fashion-store-bbdda',
    storageBucket: 'fashion-store-bbdda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkflAuZtupKOgp4Sj7N9dE2UToMP_JVUk',
    appId: '1:537962552829:ios:60840fd5cdc01bb8ed8d94',
    messagingSenderId: '537962552829',
    projectId: 'fashion-store-bbdda',
    storageBucket: 'fashion-store-bbdda.firebasestorage.app',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAR3B23ioi0PCCVe2m_RULwogjWqe4we8',
    appId: '1:537962552829:web:bbf2b44e8ad58939ed8d94',
    messagingSenderId: '537962552829',
    projectId: 'fashion-store-bbdda',
    authDomain: 'fashion-store-bbdda.firebaseapp.com',
    storageBucket: 'fashion-store-bbdda.firebasestorage.app',
    measurementId: 'G-1PTGT2K267',
  );
}
